CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE projects (id text PRIMARY KEY, name text NOT NULL, city text NOT NULL, timezone text NOT NULL DEFAULT 'Asia/Kolkata', area geometry(Polygon,4326), owner_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE network_versions (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), source text NOT NULL, sumo_version text NOT NULL, checksum text NOT NULL, validation_state text NOT NULL, artifact_path text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE road_segments (id text PRIMARY KEY, network_version_id text NOT NULL REFERENCES network_versions(id), name text, direction text NOT NULL, geometry geometry(LineString,4326) NOT NULL, lanes integer, speed_mps double precision, mapping_confidence double precision NOT NULL, provenance text NOT NULL);
CREATE INDEX road_segments_geometry_gist ON road_segments USING gist(geometry);
CREATE TABLE traffic_observations (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), road_segment_id text REFERENCES road_segments(id), provider text NOT NULL, provenance text NOT NULL, observed_at timestamptz NOT NULL, payload jsonb NOT NULL, confidence double precision, retention_expires_at timestamptz);
CREATE TABLE demand_versions (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), method text NOT NULL, confidence_grade text NOT NULL, checksum text NOT NULL, calibration jsonb NOT NULL, artifact_path text NOT NULL);
CREATE TABLE scenarios (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), title text NOT NULL, objective text NOT NULL, status text NOT NULL, source text NOT NULL, approved_by text, approved_at timestamptz);
CREATE TABLE scenario_operations (id text PRIMARY KEY, scenario_id text NOT NULL REFERENCES scenarios(id), operation_type text NOT NULL CHECK(operation_type='CLOSE_ROAD'), target_segment_id text NOT NULL REFERENCES road_segments(id), payload jsonb NOT NULL, provenance text NOT NULL);
CREATE TABLE simulation_runs (id text PRIMARY KEY, scenario_id text NOT NULL REFERENCES scenarios(id), status text NOT NULL, seed_count integer NOT NULL, engine_version text NOT NULL, configuration jsonb NOT NULL, quality jsonb NOT NULL, artifact_path text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE metric_summaries (run_id text NOT NULL REFERENCES simulation_runs(id), scope_type text NOT NULL, scope_id text, metric_name text NOT NULL, baseline_value double precision, proposal_value double precision, ci95 double precision, unit text NOT NULL);
CREATE TABLE audit_events (id bigserial PRIMARY KEY, actor_id text NOT NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, before_json jsonb, after_json jsonb, created_at timestamptz NOT NULL DEFAULT now());

