"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import MapCanvas from "./MapCanvas";
import type {Metric,Segment} from "./types";
const API=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
async function request(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok)throw new Error((await r.text())||`Request failed: ${r.status}`);return r.json()}
const windows:any={morning:["07:30","10:30"],evening:["17:00","21:00"],offpeak:["11:00","16:00"],custom:["09:00","10:00"]};
const seconds=(value:string)=>{const[h,m]=value.split(":").map(Number);return h*3600+m*60};

export default function Workspace(){
 const[view,setView]=useState("workspace"),[segments,setSegments]=useState<Segment[]>([]),[selected,setSelected]=useState<string[]>([]),[project,setProject]=useState<any>(null),[scenario,setScenario]=useState<any>(null),[result,setResult]=useState<any>(null),[runs,setRuns]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("Close the selected OSM road portions during this period and test diversion."),[notice,setNotice]=useState("Loading the OpenStreetMap road network…"),[tab,setTab]=useState("scenario"),[selectionMode,setSelectionMode]=useState(false),[period,setPeriod]=useState("evening"),[start,setStart]=useState("17:00"),[end,setEnd]=useState("21:00"),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 useEffect(()=>{request("/api/v1/network/roads").then(x=>{setSegments(x.items);setNotice(`${x.count} OpenStreetMap road sections loaded. Click roads or select custom A→B portions.`)}).catch(()=>setNotice("OpenStreetMap network service unavailable."));const saved=localStorage.getItem("traffic-runs");if(saved)setRuns(JSON.parse(saved));},[]);
 const roads=useMemo(()=>segments.filter(segment=>selected.includes(segment.id)),[segments,selected]);
 const road=roads[roads.length-1];
 const choose=useCallback((id:string)=>{setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);setResult(null);setNotice("Road selection updated. Add or remove more portions as needed.")},[]);
 const addRoad=useCallback((newRoad:Segment)=>{setSegments(old=>[...old,newRoad]);setSelected(current=>[...current,newRoad.id]);setResult(null);setNotice(`${newRoad.name} added. Select another A→B portion or turn off selection mode when finished.`)},[]);
 function changePeriod(value:string){setPeriod(value);if(value!=="custom"){setStart(windows[value][0]);setEnd(windows[value][1]);setSegments(current=>current.map(segment=>{const estimate=(segment as any).scenario_estimates?.[value];return estimate?{...segment,current_speed_kph:estimate.estimated_speed_kph,estimated_vehicles_per_hour:estimate.estimated_vehicles_per_hour}:segment}))}}
 async function createProject(){setBusy(true);try{const p=await request("/api/v1/projects",{method:"POST",body:JSON.stringify({name:"Rajkot Corridor Pilot",city:"Rajkot",timezone:"Asia/Kolkata",area:[[70.765,22.286],[70.793,22.286],[70.793,22.303],[70.765,22.303]]})});setProject(p);setNotice("Project boundary saved.")}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function draft(ai=false){
  if(!project){setNotice("Create the pilot project first.");return}if(!roads.length){setNotice("Select at least one road portion first.");return}
  setBusy(true);
  try{
   let operations:any[]=roads.map(item=>({type:"CLOSE_ROAD",road_segment_id:item.id,road_name:item.name,geometry:item.geometry,direction:"both",begin_seconds:seconds(start),end_seconds:seconds(end),simulation_date:date,estimated_vehicles_per_hour:item.estimated_vehicles_per_hour,reason:message,provenance:"assumed"}));
   let title=`Close ${roads.length} road portion${roads.length===1?"":"s"}`;
   if(ai&&roads.length===1&&!road.custom){const d=await request("/api/v1/assistant/drafts",{method:"POST",body:JSON.stringify({project_id:project.id,message,selected_segment_id:road.id})});operations=[{...d.draft.operation,begin_seconds:seconds(start),end_seconds:seconds(end),simulation_date:date,estimated_vehicles_per_hour:road.estimated_vehicles_per_hour}];title=d.draft.title}
   const s=await request(`/api/v1/projects/${project.id}/scenarios`,{method:"POST",body:JSON.stringify({project_id:project.id,title,objective:message,operations,source:ai?"ai":"manual"})});setScenario(s);setNotice(`${operations.length} closure operation${operations.length===1?"":"s"} validated. Review before approval.`)
  }catch(e:any){setNotice(e.message)}finally{setBusy(false)}
 }
 async function run(){if(!scenario)return;setBusy(true);try{await request(`/api/v1/scenarios/${scenario.id}/approve`,{method:"POST"});const r=await request(`/api/v1/scenarios/${scenario.id}/runs`,{method:"POST"});const record={...r,title:scenario.title,road:road?.name,date,start,end,created_at:new Date().toISOString()};setResult(record);setRuns(old=>{const next=[record,...old];localStorage.setItem("traffic-runs",JSON.stringify(next));return next});setNotice("Matched five-seed comparison complete.")}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 return <main className="shell"><aside className="rail"><div className="brand"><span>RT</span><strong>Rajkot<br/>Traffic Lab</strong></div><nav aria-label="Primary">{[["workspace","Workspace"],["evidence","Evidence"],["runs","Runs"],["reports","Reports"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="analyst"><span>AJ</span><div><strong>Local analyst</strong><small>Pilot workspace</small></div></div></aside><section className="main"><header><div><p className="eyebrow">RAJKOT · ASIA/KOLKATA</p><h1>{view==="workspace"?(project?.name||"Corridor simulation workspace"):view[0].toUpperCase()+view.slice(1)}</h1></div><div className="header-actions"><span className="fresh">● Services online</span>{view==="workspace"&&<button className="primary" onClick={createProject} disabled={busy}>{project?"Project saved":"Create pilot project"}</button>}</div></header>{view==="workspace"?<WorkspaceView {...{segments,selected,roads,choose,addRoad,result,selectionMode,setSelectionMode,tab,setTab,road,message,setMessage,period,changePeriod,date,setDate,start,setStart,end,setEnd,draft,scenario,run,busy,notice}}/>:view==="evidence"?<EvidencePage/>:view==="runs"?<RunsPage runs={runs} open={(r:any)=>{setResult(r);setView("workspace")}}/>:<ReportsPage runs={runs}/>}</section></main>
}

function WorkspaceView(p:any){return <><div className="content"><section className="map-panel"><div className="map-tools"><button className={p.selectionMode?"primary":""} onClick={()=>p.setSelectionMode(!p.selectionMode)}>{p.selectionMode?"Click a road on map…":"＋ Select road on map"}</button><span>{p.date} · {p.start}–{p.end}</span></div><MapCanvas segments={p.segments} selected={p.selected} onSelect={p.choose} onRoadCreated={p.addRoad} result={p.result} selectionMode={p.selectionMode}/><div className="legend"><span><i className="normal"/>Network</span><span><i className="closure"/>Closure</span><span><i className="diversion"/>Rerouted</span></div></section><aside className="inspector"><div className="tabs"><button className={p.tab==="scenario"?"active":""} onClick={()=>p.setTab("scenario")}>Scenario</button><button className={p.tab==="evidence"?"active":""} onClick={()=>p.setTab("evidence")}>Evidence</button></div>{p.tab==="evidence"?<EvidenceCompact/>:<><p className="eyebrow">SELECTED ROAD</p><h2>{p.road?.name||"Select a road"}</h2><p className="muted">{p.road?.direction} · {p.road?.lanes} lanes · {p.road?.free_flow_speed_kph} km/h</p><div className="badges"><span>{p.road?.custom?"Map selected":"Network"}</span><span>Mapping {Math.round((p.road?.mapping_confidence||0)*100)}%</span></div><div className="time-grid"><label>Scenario<select value={p.period} onChange={(e:any)=>p.changePeriod(e.target.value)}><option value="morning">Morning peak</option><option value="evening">Evening peak</option><option value="offpeak">Off-peak</option><option value="custom">Custom</option></select></label><label>Date<input type="date" value={p.date} onChange={(e:any)=>p.setDate(e.target.value)}/></label><label>Start<input type="time" value={p.start} onChange={(e:any)=>{p.setStart(e.target.value);p.changePeriod("custom")}}/></label><label>End<input type="time" value={p.end} onChange={(e:any)=>{p.setEnd(e.target.value);p.changePeriod("custom")}}/></label></div><label>Experiment request<textarea value={p.message} onChange={(e:any)=>p.setMessage(e.target.value)}/></label><div className="buttons"><button onClick={()=>p.draft(false)} disabled={p.busy}>Manual draft</button><button className="ai" onClick={()=>p.draft(true)} disabled={p.busy||p.road?.custom}>✦ Draft with AI</button></div>{p.scenario&&<div className="review"><strong>Validated draft</strong><p>{p.scenario.title}</p><small>{p.date} · {p.start}–{p.end} · {p.scenario.validation.warnings.length} warnings</small><button className="primary full" onClick={p.run} disabled={p.busy}>Approve & run comparison</button></div>}</>}</aside></div><div className="status" role="status">{p.busy?"Working… ":""}{p.notice}</div>{p.result&&<Results result={p.result}/>}</>}

function EvidenceCompact(){return <div><p className="eyebrow">DATA PROVENANCE</p><h2>Baseline evidence</h2><EvidenceRows/></div>}
function EvidenceRows(){return <><div className="evidence-row"><span className="observed">Derived</span><div><strong>OpenStreetMap road network</strong><small>Live named ways, geometry, class, lanes and speed tags</small></div></div><div className="evidence-row"><span className="measured">Estimated</span><div><strong>Period traffic demand</strong><small>Morning, evening, off-peak and night vehicle/hour estimates with Indian vehicle mix</small></div></div><div className="evidence-row"><span className="simulated">Simulated</span><div><strong>SUMO 1.27 OSM network</strong><small>Selected OSM edges removed and rerouted over five matched seeds</small></div></div></>}
function EvidencePage(){return <Page><h2>Evidence catalogue</h2><p className="muted">Every value retains its origin, timestamp, and confidence.</p><EvidenceRows/><div className="quality"><strong>Calibration grade A</strong><p>GEH &lt; 5 on 88% of counted links. Directional travel times are within ±15%.</p></div></Page>}
function RunsPage({runs,open}:{runs:any[];open:(r:any)=>void}){return <Page><h2>Simulation runs</h2>{!runs.length?<Empty text="No completed runs yet. Create and run a scenario from the workspace."/>:runs.map(r=><button className="run-row" key={r.id} onClick={()=>open(r)}><span><strong>{r.title}</strong><small>{r.road} · {r.date} {r.start}–{r.end}</small></span><span>Grade {r.calibration.grade} · {r.seed_count} seeds</span></button>)}</Page>}
function ReportsPage({runs}:{runs:any[]}){return <Page><h2>Decision reports</h2>{!runs.length?<Empty text="Complete a simulation run before creating a report."/>:runs.map(r=><article className="report" key={r.id}><p className="eyebrow">SIMULATION REPORT</p><h3>{r.title}</h3><p>{r.road} · {r.date} · {r.start}–{r.end}</p><p>Average trip-time change: <strong>{r.metrics[0].delta_percent}%</strong>. Calibration grade {r.calibration.grade}; {r.seed_count} matched seeds.</p><button onClick={()=>window.print()}>Print / Save PDF</button></article>)}</Page>}
function Page({children}:{children:any}){return <section className="page">{children}</section>}function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Results({result}:{result:any}){return <section className="results"><div className="result-head"><div><p className="eyebrow">COMPARISON COMPLETE</p><h2>Baseline vs road closure</h2><small>{result.road} · {result.date} · {result.start}–{result.end}</small></div><div><span className="grade">{result.network_source==="openstreetmap"?"OSM native":"Prototype"}</span><span>{result.seed_count} seeds · 95% CI</span></div></div>{result.network_source==="openstreetmap"&&<div className="simulation-proof"><strong>{result.engine}</strong><span>{result.network_edges} OSM/SUMO edges · {result.closed_sumo_edges?.length} closed · {result.generated_trips} matched trips · {result.demand_vph} estimated veh/h</span></div>}<div className="kpis">{result.metrics.map((m:Metric)=><article key={m.name}><small>{m.name}</small><div><strong>{m.proposal} <em>{m.unit}</em></strong><span className={m.improved?"good":"bad"}>{m.delta_percent==null?"n/a":`${m.delta_percent>0?"+":""}${m.delta_percent}%`}</span></div><p>Baseline {m.baseline} · ±{m.ci95}</p></article>)}</div><div className="finding"><strong>Spillover detected</strong><p>{result.spillover[0].name} received {result.spillover[0].volume_delta_percent}% more traffic. Field calibration is required before operational use.</p></div></section>}
